name: .NET

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    env:
      ProjectName: AuthenticatorChooser

    runs-on: windows-latest

    strategy:
      matrix:
        include:
          - targetPlatform: win-x64
          - targetPlatform: win-arm64

    steps:
    - name: Clone
      uses: actions/checkout@v4
        
    - name: Restore
      run: dotnet restore --locked-mode --verbosity normal

    - name: Build
      run: dotnet build ${{ env.ProjectName }} --no-restore --runtime ${{ matrix.targetPlatform }} --configuration Release --no-self-contained

    - name: Publish
      run: dotnet publish ${{ env.ProjectName }} --no-build --runtime ${{ matrix.targetPlatform }} --configuration Release --no-self-contained -p:PublishSingleFile=true

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ProjectName }}-${{ matrix.targetPlatform }}
        path: ${{ env.ProjectName }}/bin/Release/net8.0-windows/${{ matrix.targetPlatform }}/publish/*.exe
        path: ${{ env.ProjectName }}/bin/Release/net8.0-windows/${{ matrix.targetPlatform }}/publish/*.pdb
        if-no-files-found: error
